spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

zookeeper:
  connectionString: 192.168.0.244:2181/leader

kafka:
  bootstrap:
    servers: 192.168.0.244:9092

topics: subject00,subject01,subject02,subject03,subject04,subject05,subject06,subject07,subject08,subject09

subject:
  limit: 80