spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

zookeeper:
  connectionString: your.zookeeper.ip.address:2181/znode-name

kafka:
  bootstrap:
    servers: